export const european_countries = [
    { name: 'Albania', country: 'AL' },
    { name: 'Andorra', country: 'AD' },
    { name: 'Armenia', country: 'AM' },
    { name: 'Austria', country: 'AT' },
    { name: 'Azerbaijan', country: 'AZ' },
    { name: 'Belarus', country: 'BY' },
    { name: 'Belgium', country: 'BE' },
    { name: 'Bosnia and Herzegovina', country: 'BA' },
    { name: 'Bulgaria', country: 'BG' },
    { name: 'Croatia', country: 'HR' },
    { name: 'Cyprus', country: 'CY' },
    { name: 'Czech Republic', country: 'CZ' },
    { name: 'Denmark', country: 'DK' },
    { name: 'Estonia', country: 'EE' },
    { name: 'Finland', country: 'FI' },
    { name: 'France', country: 'FR' },
    { name: 'Georgia', country: 'GE' },
    { name: 'Germany', country: 'DE' },
    { name: 'Greece', country: 'GR' },
    { name: 'Hungary', country: 'HU' },
    { name: 'Iceland', country: 'IS' },
    { name: 'Ireland', country: 'IE' },
    { name: 'Italy', country: 'IT' },
    { name: 'Kazakhstan', country: 'KZ' },
    { name: 'Kosovo', country: 'XK' },
    { name: 'Latvia', country: 'LV' },
    { name: 'Liechtenstein', country: 'LI' },
    { name: 'Lithuania', country: 'LT' },
    { name: 'Luxembourg', country: 'LU' },
    { name: 'Malta', country: 'MT' },
    { name: 'Moldova', country: 'MD' },
    { name: 'Monaco', country: 'MC' },
    { name: 'Montenegro', country: 'ME' },
    { name: 'Netherlands', country: 'NL' },
    { name: 'North Macedonia', country: 'MK' },
    { name: 'Norway', country: 'NO' },
    { name: 'Poland', country: 'PL' },
    { name: 'Portugal', country: 'PT' },
    { name: 'Romania', country: 'RO' },
    { name: 'Russia', country: 'RU' },
    { name: 'San Marino', country: 'SM' },
    { name: 'Serbia', country: 'RS' },
    { name: 'Slovakia', country: 'SK' },
    { name: 'Slovenia', country: 'SI' },
    { name: 'Spain', country: 'ES' },
    { name: 'Sweden', country: 'SE' },
    { name: 'Switzerland', country: 'CH' },
    { name: 'Turkey', country: 'TR' },
    { name: 'Ukraine', country: 'UA' },
    { name: 'United Kingdom', country: 'GB' },
    { name: 'Vatican City', country: 'VA' }
];
